spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yoriking_joriking?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: kim
    password: kimpw