spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}/yoriking_joriking?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: kg
    password: rlarldnjs1!