spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none

management:
  endpoints:
    web:
      exposure:
        include: info, health
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true