name: Deploy External API to EC2

on:
  push:
    branches:
      fix/github-action

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: my-githubaction-code-save-bucket
  CODE_DEPLOY_APPLICATION_NAME: my-codedeploy-app-deploy-on-ec2
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: my-deploy-ec2-servers
  APP_SPEC_PATH: applications/yoriking-app-external-api

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      # (1) 코드 체크아웃
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: fix/github-action

      # (2) JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # (3) gradlew 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # (4) Gradle build (Test 제외)
      - name: Build with Gradle
        run: ./gradlew clean :applications:yoriking-app-external-api:build -x test

      # (5) AWS 인증 (IAM 사용자 Access Key, Secret Key 활용)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # (6) 빌드 결과물을 S3 버킷에 업로드
      - name: Upload to AWS S3
        run: |
          aws deploy push \
            --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
            --ignore-hidden-files \
            --s3-location s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip \
            --source $APP_SPEC_PATH

      # (7) S3 버킷에 있는 파일을 대상으로 CodeDeploy 실행
      - name: Deploy to AWS EC2 from S3
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
            --s3-location bucket=$S3_BUCKET_NAME,key=$GITHUB_SHA.zip,bundleType=zip